[workspace]
members = [
    "./minimal",
]
resolver = "3"

[workspace.dependencies]
bevy = { version = "0.18", features = ["file_watcher"] }
hachiya = { path = "../../" }
stabby = { version = "72.1.1" }

